// Package sipua implements the SIP user-agent behavior SwarmDialer needs:
// registering as a PBXware extension and (later) placing/receiving calls.
package sipua

import (
	"context"
	"fmt"
	"time"

	"github.com/emiago/sipgo"
	"github.com/emiago/sipgo/sip"
	"github.com/icholy/digest"
)

// Endpoint is one PBXware extension's SIP registration credentials, as
// produced by the provisioning module (see internal/pbxware and
// extensions.json).
type Endpoint struct {
	// Username is the SIP auth username, e.g. "999200" (tenant_code+ext) —
	// PBXware's convention, confirmed via pbxware.ext.configuration.
	Username string
	Password string
	// AOR is the extension number to register as, e.g. "200".
	AOR string
}

// Register performs a single SIP REGISTER, handling the 401 digest-auth
// challenge PBXware sends back, following the pattern from sipgo's own
// example/register/client.
//
// dialDestination is the actual network target (host:port) the request is
// sent to. sipDomain is the domain used inside the SIP headers (Request-URI,
// From, To) — normally the same as dialDestination, but PBXware's
// multi-tenant setup may expect the tenant's own FQDN (its tenant_name) here
// instead of the bare server IP, since dialDestination isn't necessarily
// resolvable via DNS. localHost is our own advertised Contact address (no
// port — the client picks an ephemeral one unless configured otherwise).
//
// Returns the expiry PBXware granted, in seconds, so the caller knows when to
// re-register.
func Register(ctx context.Context, client *sipgo.Client, dialDestination, sipDomain, localHost string, ep Endpoint, expirySeconds int) (int, error) {
	recipient := sip.Uri{}
	if err := sip.ParseUri(fmt.Sprintf("sip:%s@%s", ep.AOR, sipDomain), &recipient); err != nil {
		return 0, fmt.Errorf("parsing recipient URI: %w", err)
	}

	req := sip.NewRequest(sip.REGISTER, recipient)
	req.SetDestination(dialDestination)

	// sipgo's ClientRequestRegisterBuild only fills in default From/To headers
	// when they're missing, and its default From uses the UA's generic name
	// ("sipgo"), not our real SIP identity — which PBXware then can't match to
	// any endpoint and rejects with 403 before ever offering a digest
	// challenge. Build both explicitly with ep.Username instead.
	identity := sip.Uri{Scheme: "sip", User: ep.Username, Host: recipient.Host, Port: recipient.Port}
	from := sip.FromHeader{DisplayName: ep.Username, Address: identity}
	from.Params = sip.NewParams()
	from.Params.Add("tag", sip.GenerateTagN(16))
	req.AppendHeader(&from)
	req.AppendHeader(&sip.ToHeader{DisplayName: ep.Username, Address: identity})

	req.AppendHeader(sip.NewHeader("Contact", fmt.Sprintf("<sip:%s@%s>", ep.Username, localHost)))
	req.AppendHeader(sip.NewHeader("Expires", fmt.Sprint(expirySeconds)))
	req.SetTransport("UDP")

	res, err := doTransaction(ctx, client, req, sipgo.ClientRequestRegisterBuild)
	if err != nil {
		return 0, err
	}

	if res.StatusCode == sip.StatusUnauthorized {
		wwwAuth := res.GetHeader("WWW-Authenticate")
		if wwwAuth == nil {
			return 0, fmt.Errorf("got 401 with no WWW-Authenticate header")
		}
		chal, err := digest.ParseChallenge(wwwAuth.Value())
		if err != nil {
			return 0, fmt.Errorf("parsing digest challenge: %w", err)
		}
		// The digest "uri" must exactly match the request's Request-URI as
		// sent on the wire: "sip:<domain>" with no user part (sipgo's
		// ClientRequestRegisterBuild strips the user for REGISTER per RFC
		// 3261). A mismatch here (e.g. missing scheme/port) previously caused
		// Asterisk to compute a different hash and reject with 403 even after
		// a correct challenge.
		cred, err := digest.Digest(chal, digest.Options{
			Method:   req.Method.String(),
			URI:      "sip:" + sipDomain,
			Username: ep.Username,
			Password: ep.Password,
		})
		if err != nil {
			return 0, fmt.Errorf("computing digest response: %w", err)
		}

		authReq := req.Clone()
		authReq.RemoveHeader("Via") // regenerated by the transport layer
		authReq.AppendHeader(sip.NewHeader("Authorization", cred.String()))

		res, err = doTransaction(ctx, client, authReq, sipgo.ClientRequestIncreaseCSEQ, sipgo.ClientRequestAddVia)
		if err != nil {
			return 0, err
		}
	}

	if res.StatusCode != sip.StatusOK {
		return 0, fmt.Errorf("registration failed: %d %s", res.StatusCode, res.Reason)
	}

	if exp := res.GetHeader("Expires"); exp != nil {
		var granted int
		if _, err := fmt.Sscanf(exp.Value(), "%d", &granted); err == nil && granted > 0 {
			return granted, nil
		}
	}
	return expirySeconds, nil
}

// KeepRegistered registers ep and keeps re-registering at ~80% of the granted
// expiry until ctx is canceled. errs receives any registration failure
// (initial or refresh); the caller decides whether that's fatal.
func KeepRegistered(ctx context.Context, client *sipgo.Client, dialDestination, sipDomain, localHost string, ep Endpoint, errs chan<- error) {
	const defaultExpiry = 300
	for {
		granted, err := Register(ctx, client, dialDestination, sipDomain, localHost, ep, defaultExpiry)
		if err != nil {
			select {
			case errs <- fmt.Errorf("extension %s: %w", ep.AOR, err):
			case <-ctx.Done():
			}
			return
		}

		refresh := time.Duration(float64(granted)*0.8) * time.Second
		select {
		case <-ctx.Done():
			return
		case <-time.After(refresh):
		}
	}
}

func doTransaction(ctx context.Context, client *sipgo.Client, req *sip.Request, opts ...sipgo.ClientRequestOption) (*sip.Response, error) {
	tx, err := client.TransactionRequest(ctx, req, opts...)
	if err != nil {
		return nil, fmt.Errorf("creating transaction: %w", err)
	}
	defer tx.Terminate()

	select {
	case <-tx.Done():
		return nil, fmt.Errorf("transaction ended with no response")
	case res := <-tx.Responses():
		return res, nil
	case <-ctx.Done():
		return nil, ctx.Err()
	}
}
